services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    # ports:
    #   - "${REDIS_PORT}:${REDIS_INTERNAL_PORT}"
    command: redis-server --port 6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    # network_mode: "host"

  backend:
    # image: mika1512/pcap-catalog-service:2.5.0
    build: .
    container_name: backend
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${BE_BASE_PORT}:${BE_INTERNAL_PORT}"
    volumes:
      - "${PCAP_DIRECTORIES}:${PCAP_MOUNTED_DIRECTORY}:ro"
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request, sys, os; url=f'http://localhost:${BE_INTERNAL_PORT}/health'; urllib.request.urlopen(url)\""]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    # image: mika1512/pcap-frontend-app:1.5.0
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${FRONTEND_PORT}:${NGINX_PORT}"
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${NGINX_PORT} >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    # backend_logs:

networks:
  app_network:
    driver: bridge
